name: Create Artifact for ios
description: "ios module buildし、outputをartifactへUpload。 ※事前にFlutter Installが必要"

inputs:
  flavor:
    description: "envを指定。(stg/dev)"
    required: true
  build-target:
    description: "ビルドターゲット（all[規定]/release-only）"
    default: all

runs:
  using: 'composite'
  steps:
      - if: inputs.build-target == 'all'
        run: |
          cd ${GITHUB_WORKSPACE}/repository
          echo 'target:all'
          echo ${{ inputs.build-target }}
          echo ${{ inputs.flavor }}
        shell: bash

      - if: inputs.build-target == 'release-only'
        run: |
          cd ${GITHUB_WORKSPACE}/repository
          echo 'target:release-only'
          echo ${{ inputs.build-target }}
          echo ${{ inputs.flavor }}
          echo $(echo ${{ inputs.flavor }} | sed 's/env\///')
          touch ${{ github.workspace }}/test.txt
        shell: bash

      - name: set artifact name
        run: echo  'artifact-name'$(echo ${{ inputs.flavor }} | sed 's/env\///') >> $GITHUB_ENV 

      - name: upload artifact
        uses: actions/upload-artifact@v3.1.1
        with: 
          name: ${{ $env.artifact-name }} 
          path: ${{ github.workspace }}/*
          retention-days: 15
