name: "Flutter module create artifact for ios"
description: "Flutter moduleのiosビルドとアーティファクト作成を実行、呼び出し時はFlutter Install済みであること"

inputs:
  flavor:
    required: true
  build-target:
    default: all

runs:
  using: 'composite'
  steps:
      - name: flutter build
        if: ${{ inputs.build-target }} == 'all'
        run: |
          echo "all build"
        shell: bash

      - name: flutter build release only
        if: ${{ inputs.build-target }} == 'release'
        run: |
          echo "release build"
        shell: bash
