name: "Flutter module create artifact for ios"
description: "Flutter moduleのiosビルドとアーティファクト作成を実行、呼び出し時はFlutter Install済みであること"

inputs:
  flavor:
    required: true
runs:
  using: 'composite'
  steps:
      - name: flutter build
        run: |
          cd ${GITHUB_WORKSPACE}/repository
          flutter build ios-framework --cocoapods --dart-define flavor=${{ inputs.flavor }}
        shell: bash

      - name: upload artifact
        uses: actions/upload-artifact@v3.1.1
        with: 
          name: ios_${{ inputs.flavor }}
          # ${GITHUB_WORKSPACE}は利用不可 https://github.com/actions/upload-artifact/issues/110
          path: ${{ github.workspace }}/repository/build/ios/framework/*
          retention-days: 1
