name: Create Artifact for ios
description: "ios module buildし、outputをartifactへUpload。 ※事前にFlutter Installが必要"

inputs:
  flavor:
    description: "envを指定。(stg/dev)"
    required: true
  build-target:
    description: "ビルドターゲット（all[規定]/release-only）"
    default: all

runs:
  using: 'composite'
  steps:
      - if: inputs.build-target == 'all'
        run: |
          cd ${GITHUB_WORKSPACE}/repository
          echo 'target:all'
          echo ${{ inputs.build-target }}
          echo ${{ inputs.flavor }}
        shell: bash

      - if: inputs.build-target == 'release-only'
        run: |
          cd ${GITHUB_WORKSPACE}/repository
          echo 'target:release-only'
          echo ${{ inputs.build-target }}
          echo ${ inputs.flavor }
        shell: bash
