name: "Flutter module create artifact for ios"
description: "Flutter moduleのiosビルドとアーティファクト作成を実行、呼び出し時はFlutter Install済みであること"

inputs:
  flavor:
    required: true

env:
  build_path: ${{ github.workspace }}/repository/build-${{ inputs.flavor }}

runs:
  using: 'composite'
  steps:
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.build_path }}/*
            ${{ github.workspace }}/repository/.dart_tool
            ${{ github.workspace }}/repository/.ios/*
            ${{ runner.tool_cache }}/.pub-cache
            ${{ runner.tool_cache }}/.cocoapods
          key: build-${{ inputs.flavor }}-${{ hashFiles('${{ github.workspace }}/repository/pubspec.lock') }}
          restore-keys: |
            build-${{ inputs.flavor }}-${{ hashFiles('${{ github.workspace }}/repository/pubspec.lock') }}
            build-${{ inputs.flavor }}-
            build-

      - name: flutter build
        run: |
          cd ${{ github.workspace }}/repository
          flutter build ios-framework --cocoapods --output=${{ env.build_path }} --dart-define flavor=${{ inputs.flavor }}
        shell: bash

      - name: upload artifact
        uses: actions/upload-artifact@v3.1.1
        with: 
          name: ios_${{ inputs.flavor }}
          # ${GITHUB_WORKSPACE}は利用不可 https://github.com/actions/upload-artifact/issues/110
          path: ${{ env.build_path }}/*
          retention-days: 1
