name: Install Flutter

on:
  push:
    branches:
        - release/*

jobs:
  build:
      runs-on: ubuntu-latest
      timeout-minutes: 15
      
      steps:
      
      - uses: actions/checkout@v2
        with:
          path: 'repository'
          
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1
        with:
          version: 3.0.4

      - name: Run flutter doctor
        run: flutter doctor
        
      - name: Run flutter build
        run: |
          cd ${GITHUB_WORKSPACE}/repository
          flutter build aar --no-debug --no-profile --pub

      - uses: actions/upload-artifact@v3.1.1
        with: 
          name: aar
          # ${GITHUB_WORKSPACE}は利用不可 https://github.com/actions/upload-artifact/issues/110
          path: ${{ github.workspace }}/repository/build/host/outputs/repo/com/example/ci_test/*
          retention-days: 1
