name: Release for ios

on:
  push:
    branches:
        - pre-release/*
        - release/*

env:
  flutter_ver: 3.0.4
  flutter_path: ${{ github.workspace }}/_flutter

jobs:
  flutter-setup:
    runs-on: macOS-11
    timeout-minutes: 30
    
    steps:
      - if: startsWith(github.ref, 'refs/heads/release/')
        - run: echo 'release branch'
      - if: startsWith(github.ref, 'refs/heads/pre-release/')
        - run: echo 'pre branch'

    # - name: flutter build and create artifact 'stg'
    #   if: startsWith(github.ref_name, 'pre-release')
    #   uses: ./repository/.github/workflows/create_artifact_ios
    #   with:
    #     flavor: 'stg'
    #     build-target: release

    # - name: flutter build and create artifact 'aaa'
    #   if: startsWith(github.ref_name, 'release')
    #   uses: ./repository/.github/workflows/create_artifact_ios
    #   with:
    #     flavor: 'stg'
