name: Release for ios

on:
  push:
    branches:
        - release/*

jobs:
  ios-release:
      runs-on: macOS-11
      timeout-minutes: 30
      
      steps:
      
      - uses: actions/checkout@v3
        with:
          path: 'repository'
          
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1
        with:
          version: 3.0.4

      - name: Run flutter doctor
        run: |
          flutter doctor

      - name: Run flutter pub get
        run: |
          cd repository
          flutter pub get

      - name: Cache flutter-dir and packages
        uses: actions/cache@v3
        with:
          path: |
            ./repository/*
            ~/.packages
          key: packages-${{ hashFiles('./repository/pubspec.lock') }}
          restore-keys: |
            packages-

      - name: flutter build and create artifact 'stg'
        uses: ./repository/.github/workflows/create_artifact_ios
        with:
          flavor: 'stg'

      - name: flutter build and create artifact 'prod'
        uses: ./repository/.github/workflows/create_artifact_ios
        with:
          flavor: 'prod'

      - name: Cache build
        uses: actions/cache@v2
        with:
          path: |
            ./repository/build/*
          key: build-${{ hashFiles('./repository/pubspec.lock') }}
          restore-keys: |
            build-
