name: Release for ios

on:
  push:
    branches:
        - release/*

env:
  flutter_ver: 3.0.4
  flutter_path: ${GITHUB_WORKSPACE}/_flutter

jobs:
  ios-release:
      runs-on: macOS-11
      timeout-minutes: 30
      
      steps:
      
      - uses: actions/checkout@v3
        with:
          path: 'repository'
          
      - name: Setup Flutter
        run: |
          ${GITHUB_WORKSPACE}/repository/.github/workflows/scripts/install-flutter.sh -v ${{ env.flutter_ver }} -p ${{ env.flutter_path }}

      - name: Cache flutter setup
        id: flutter_setup
        uses: actions/cache@v3
        with:
          path: ${{ env.flutter_path }}/
          key: flutter-${{ env.flutter_ver }}

      - name: Run flutter doctor
        if: steps.flutter_setup.outputs.cache-hit != 'true'
        run: |
          flutter doctor

      - name: Run flutter pub get
        run: |
          cd repository
          flutter pub get

      # - name: flutter build and create artifact 'stg'
      #   uses: ./repository/.github/workflows/create_artifact_ios
      #   with:
      #     flavor: 'stg'

      # - name: flutter build and create artifact 'prod'
      #   uses: ./repository/.github/workflows/create_artifact_ios
      #   with:
      #     flavor: 'prod'
