name: release for ios

on:
  push:
    branches:
        - release/*
        - pre-release/*

jobs:
  release-ios:
      runs-on: macOS-11
      timeout-minutes: 60
      
      steps:
      
      - uses: actions/checkout@v2
        with:
          path: 'repository'
          
      # pre-release
      - name: create artifact 'stg'
        if: startsWith(github.ref_name, 'pre-release')
        uses: ./repository/.github/workflows/create_artifact_ios
        with:
          flavor: 'stg'
          build-target: release-only

      - name: create artifact 'prod'
        if: startsWith(github.ref_name, 'pre-release')
        uses: ./repository/.github/workflows/create_artifact_ios
        with:
          flavor: 'prod'
          build-target: release-only

      # release
      - name: create artifact 'stg'
        if: startsWith(github.ref_name, 'release')
        uses: ./repository/.github/workflows/create_artifact_ios
        with:
          flavor: 'stg'

      - name: create artifact 'prod'
        if: startsWith(github.ref_name, 'release')
        uses: ./repository/.github/workflows/create_artifact_ios
        with:
          flavor: 'prod'
