name: Release for ios

on:
  push:
    branches:
        - release/*

jobs:
  ios-release:
      runs-on: macOS-11
      timeout-minutes: 30
      
      steps:
      
      - uses: actions/checkout@v3
        with:
          path: 'repository'
          
      - name: Setup Flutter
        run: |
          ${GITHUB_WORKSPACE}/repository/.github/workflows/scripts/install-flutter.sh

      - name: Run flutter doctor
        run: |
          flutter doctor

      - name: Run flutter pub get
        run: |
          cd repository
          flutter pub get

      - name: flutter build and create artifact 'stg'
        uses: ./repository/.github/workflows/create_artifact_ios
        with:
          flavor: 'stg'

      - name: flutter build and create artifact 'prod'
        uses: ./repository/.github/workflows/create_artifact_ios
        with:
          flavor: 'prod'
