name: Release for ios

on:
  push:
    branches:
        - release/*

jobs:
  ios-release:
      runs-on: macOS-11
      timeout-minutes: 30
      
      steps:
      
      - uses: actions/checkout@v3
        with:
          path: 'repository'
          
      - name: Setup Flutter
        run: |
          ${GITHUB_WORKSPACE}/repository/.github/workflows/scripts/install-flutter.sh

      # - name: Cache flutter install
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ./repository/*
      #     key: install-${{ hashFiles('./repository/.github/workflows/scripts/install-flutter.sh') }}
      #     restore-keys: |
      #       install-

      - name: Run flutter doctor
        run: |
          flutter doctor
          cd repository
          flutter pub get

      - name: Run flutter pub get
        run: |
          cd repository
          flutter pub get

      - name: Cache flutter-dir and packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: packages-${{ hashFiles('./repository/pubspec.lock') }}
          restore-keys: |
            packages-

      - name: flutter build and create artifact 'stg'
        uses: ./repository/.github/workflows/create_artifact_ios
        with:
          flavor: 'stg'

      - name: Cache build stg
        uses: actions/cache@v3
        with:
          path: |
            ./repository/build/*
            ./repository/.ios/*
            ~/.pub-cache
          key: build-stg-${{ hashFiles('./repository/pubspec.lock') }}
          restore-keys: |
            build-stg-

      - name: flutter build and create artifact 'prod'
        uses: ./repository/.github/workflows/create_artifact_ios
        with:
          flavor: 'prod'

      - name: Cache build prod
        uses: actions/cache@v3
        with:
          path: |
            ./repository/build/*
            ./repository/.ios/*
            ~/.pub-cache
          key: build-prod-${{ hashFiles('./repository/pubspec.lock') }}
          restore-keys: |
            build-prod-
